
[features]
seeds = false
skip-lint = false
[programs.localnet]
register_camper = "4K4jS5PjPP2EPRrFF4EwxzZLNK3t7JVjSXqTG2d6Nn12"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/yasseen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
